version: '3.8'

networks:
  proxy:
  nextcloud:

services:

#--- MariaDB ---#

  db:
    image: mariadb:11.2.2
    container_name: database
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /mnt/md0/nextcloud/db:/var/lib/mysql
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=YourPassword
      - MYSQL_PASSWORD=YourPassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

#--- Redis ---#

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server
    networks:
      - nextcloud

#--- NextCloud ---#

  app:
    image: nextcloud:stable
    container_name: nextcloud
    restart: always
    #ports:
    # - 80:80
    links:
      - db
      - redis
    volumes:
      - /md0/nextcloud/app:/var/www/html
    networks:
      - nextcloud
      - proxy
    environment:
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=YourPassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

#--- Proxy ---#
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/md0/data:/data
      - /mnt/md0/proxy/letsencrypt:/etc/letsencrypt
    networks:
      - proxy